### ISSUE TITLE
unable to use send for nested hashes

### ISSUE THREAD

**Issue by tjbarker** [adsteel/hash_dot#13]
I have written functionality to allow for the following specs to pass.
I am interested in creating a pr but permissions are blocking me.

`... spec/hash_dot_spec.rb`
```
   it "allows dot send access for a nested instance" do
      one = { a: { b: 1 } }.to_dot

      expect( one.send('a.b') ).to eq( 1 )
    end

    it "allows dot send set for a nested instance" do
      one = { a: { b: nil } }.to_dot
      one.send("a.b=", 1)

      expect( one.send("a.b") ).to eq( 1 )
      expect( one.a.b ).to eq( 1 )
    end
```

**Comment by adsteel** [comment]
@tjbarker have you tried forking and opening a PR from the fork? Someone else was able to recently, so that should be doable.

**Comment by adsteel** [comment]
Addressed in https://github.com/adsteel/hash_dot/pull/21
