### ISSUE TITLE
#to_dot doesn't traverse arrays

### ISSUE THREAD

**Issue by afeld** [adsteel/hash_dot#18]
Test case:

```ruby
require 'hash_dot'
{foo: {bar: 1}}.to_dot.foo.bar
#=> 1
{foo: [{bar: 1}]}.to_dot.foo.first.bar
#=> NoMethodError: undefined method `bar' for {:bar=>1}:Hash
# from /Users/aidan/.rvm/gems/ruby-2.5.0/gems/hash_dot-2.2.0/lib/hash.rb:17:in `method_missing
```

Thanks!

**Comment by adsteel** [comment]
@afeld this is as expected. Suppose you have this structure:

```ruby
{foo: [{bar: 1}, {bar: 2}]}
```

What should `foo.bar` return?

I think what you're looking for is maybe more of a hash querying tool, which I've thought a bit about but couldn't come up with a good solution for. The best solution I've come up with is wrapping the hash in a class and building specific getters and setters.

```ruby
class HashWrapper
  def initialize(hash)
    @hash = hash
  end

  def foo
    @hash[:foo]
  end

  def bar(val)
    foo.select { |obj| obj[:bar] == val
  end
end
```

This lets you define how you want to traverse your structure.

**Comment by afeld** [comment]
@adsteel I think you may have missed the `.first` in my example 😉 

> Suppose you have this structure:
> 
> ```ruby
> {foo: [{bar: 1}, {bar: 2}]}
> ```
>
> What should foo.bar return?

`NoMethodError`, but I would expect `obj.foo[0].bar` to return `1`.

**Comment by adsteel** [comment]
Ah yes I did. Interesting. Yeah, this should be a feature. Want to open a PR?
