### ISSUE TITLE
Conflicts with Arel/ActiveRecord

### ISSUE THREAD

**Issue by dishcandanty** [adsteel/hash_dot#3]
I don't know how to best describe this, or even how to go about properly debugging. Just pulled my hair out for hours then by happen stance disabled this gem and my issues were resolved. I've done multiple tests to verify that indeed, I can introduce my problem just by enabling this gem. 

If I have:

```
require 'hash_dot'
Hash.use_dot_syntax = true
```

I Receive on a nested association query:

```
Association named 'to_ary' was not found on GameData; perhaps you misspelled it? (ActiveRecord::AssociationNotFoundError)
```

I believe its specifically interferring with the arel table. Which I imagine is using hash and maybe a .method I'm replacing? Maybe .name?

I was going to stick this on stackoverflow, but I figured since its specifically related to the gem, this would be the right place.

**Comment by adsteel** [comment]
@dishcandanty That's interesting. Could you provide an example app that demonstrates the issue?

**Comment by bolanrewaju** [comment]
@dishcandanty It will be helpful if you can provide a code sample that produces this error so that someone can reproduce it and hopefully provide a solution .

**Comment by dishcandanty** [comment]
Sorry! I missed the notice and have moved on from the project. Im going to close as I don't have an example to reproduce
