### ISSUE TITLE
Traversing arrays does not work with send

### ISSUE THREAD

**Issue by eni9889** [adsteel/hash_dot#30]
I have this object:

```
data = {
        "_json" =>
            [{ "object" =>
                   { "user" =>
                         { "name" => "Ray" }
                   }
             }]
    }
```

The following works:
```
data._json[0].object.user.name
```

But this does not:
```
data.send('_json[0].object.user.name')
```

**Comment by adsteel** [comment]
@eni9889 interesting use case! Fixing this might mean that we need to add a hack to `send`, which sounds tricky and maybe not worth it? Or maybe it is. Would you be interested in putting up a PR with a possible implementation, or maybe sketching one out in this issue so we could talk pros and cons?

**Comment by adsteel** [comment]
@eni9889 the more I think about, the more I think this should be considered expected behavior. This is not how ruby works for nested methods, e.g.

```ruby
obj = { a: { b: 1 } }
obj.dig(:a, :b) # => 1
obj.send("dig(:a, :b)")
```

It would have to be:

```
obj.send("dig", *:a, :b)
```

So in your case, it would have to be more like:

```
data.send('_json').send(:[], 0).send(:object).send(:user).send(:name)
```
And that should work with hash dot as well as with normal Ruby objects.

**Comment by adsteel** [comment]
@eni9889 I'm going to close this as I think extending Ruby to work this way seems more like a separate hack of `send` than it is of making a Hash respond to dot notation.
