### ISSUE TITLE
Breaks ActiveRecord order(field: :desc) syntax when gem is used in Rails project

### ISSUE THREAD

**Issue by bousquet** [adsteel/hash_dot#31]
Prevents the project from passing a hash into the "order" clause of activerecord.  If we add a "require: false" to the gemfile for hash_dot then it avoids causing problems with activerecord.  

![Screen Shot 2020-09-28 at 11 39 15 AM](https://user-images.githubusercontent.com/1347/94472424-92c83200-017f-11eb-9057-4e5d26e07017.png)

**Comment by adsteel** [comment]
@bousquet Interesting. I'm not using this gem, but any idea what the root of the issue might be?

**Comment by stefsava** [comment]
With 2.4.2 I have not this issue.
@bousquet please verify.

**Comment by adsteel** [comment]
Closing due to lack of information.
