### ISSUE TITLE
#respond_to? should be true if the property exists

### ISSUE THREAD

**Issue by aselder** [adsteel/hash_dot#7]
Since `hash_dot` does not override `respond_to?` we get weird inconsistent results which can screw up other libraries. (e.g. SimpleDelegator)

```
[12] pry()> hash = {'foo' => 'bar'}.to_dot
=> {"foo"=>"bar"}
[13] pry()> hash.foo
=> "bar"
[14] pry()> hash.respond_to?(:foo)
=> false
```

This should be fairly easy to accomplish. I'll try and put together a pull request this weekend.

**Comment by adsteel** [comment]
Addressed with https://github.com/adsteel/hash_dot/pull/8
